In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [38]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report

In [3]:
path = '/Users/raisaurabh04/OneDrive/GreyAtom/Practice Dataset/bank_gradient_boosting_pratice.csv'

In [4]:
#Loading of the data
data = pd.read_csv(path)

data.head()


#Extracting the features
X = data.iloc[ : , : -1]

#Extracting the target class
y = data['deposit'].copy()

#Splitting the dataset into test and train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#Fitting of Weak Classifier
dt_clf = DecisionTreeClassifier(max_depth=1, random_state=0)

dt_clf.fit(X_train, y_train)

dt_score = dt_clf.score(X_test, y_test)
print(dt_score)



# Fitting of weak classifier with Adaboost

ada_clf = AdaBoostClassifier(base_estimator=dt_clf, random_state=0)

ada_clf.fit(X_train, y_train)

ada_score = ada_clf.score(X_test, y_test)

print(ada_score)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,1
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,1
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,1
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,1
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,1

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

0.7094655120931621

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=0,
                                                         splitter='best'),
                   learning_rate=1.0, n_estimators=50, random_state=0)

0.8244252015527023

In [5]:
gb_clf = GradientBoostingClassifier(random_state=0)

gb_clf.fit(X_train, y_train)

gb_score = gb_clf.score(X_test, y_test)
print(gb_score)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

0.8462227530606151

In [6]:
xgb_clf = XGBClassifier(base_estimator=dt_clf,random_state=0)

xgb_clf.fit(X_train, y_train)

gb_score = xgb_clf.score(X_test,y_test)

gb_score

XGBClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                    criterion='gini',
                                                    max_depth=1,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort=False,
                                                    random_state=0,
                                                    splitter='best'),
              base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

0.8438339802926247


# XGBoost Assessment

In [7]:
path = '/Users/raisaurabh04/OneDrive/GreyAtom/Practice Dataset/customer_assesment_xgboost.csv'

In [8]:
df = pd.read_csv(path)

df.head()

X = df.iloc[ : , 1 : -1]

y = df.iloc[ : , -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
X_train.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [10]:
X_train[X_train['TotalCharges'] == ' ']

X_train['TotalCharges'].replace(' ', np.nan, inplace=True)

X_test['TotalCharges'].replace(' ', np.nan, inplace=True)

X_train['TotalCharges'] = X_train['TotalCharges'].astype('float64')

X_test['TotalCharges'] = X_test['TotalCharges'].astype('float64')

X_train['TotalCharges'].fillna(X_train['TotalCharges'].mean(), inplace=True)

X_test['TotalCharges'].fillna(X_test['TotalCharges'].mean(), inplace=True)

X_train.isna().sum()
X_test.isna().sum()

label_encoder = LabelEncoder()

for cols in X_train.select_dtypes(exclude=np.number):
    X_train[cols] = label_encoder.fit_transform(X_train[cols])
    X_test[cols] = label_encoder.fit_transform(X_test[cols])

mapping_dict = {'Yes' : 1, 'No' : 0}

y_train = y_train.map(mapping_dict)

y_test = y_test.map(mapping_dict)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [29]:
X_train.head()
y_train.head()
X_test.head()
y_test.head()

ada_model = AdaBoostClassifier(random_state=0)

ada_model.fit(X_train, y_train)

y_pred = ada_model.predict(X_test)

ada_cm = confusion_matrix(y_test, y_pred)

ada_cr = classification_report(y_test, y_pred)
ada_score = accuracy_score(y_test, y_pred)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
3580,0,0,0,1,9,1,0,0,0,0,2,2,2,2,0,1,3,72.90,651.40
2364,1,0,1,0,14,1,2,1,0,2,2,0,0,0,0,1,2,82.65,1185.00
6813,0,0,1,0,64,0,1,0,2,0,2,2,0,2,2,0,2,47.85,3147.50
789,1,0,0,0,72,1,2,0,2,2,2,2,0,0,2,0,0,69.65,4908.25
561,1,0,1,0,3,1,2,2,1,1,1,1,1,1,0,1,3,23.60,89.05

3580    1
2364    0
6813    1
789     0
561     0
Name: Churn, dtype: int64

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
2200,0,0,0,0,19,1,0,0,0,2,0,0,2,0,1,0,2,58.20,1045.25
4627,1,0,0,0,60,1,2,1,2,2,2,2,2,2,1,1,1,116.60,7049.50
3225,0,0,0,0,13,1,0,0,2,0,0,0,2,2,0,1,2,71.95,923.85
2828,1,0,0,0,1,1,0,2,1,1,1,1,1,1,2,0,3,20.45,20.45
3768,0,0,1,0,55,1,2,1,0,2,0,0,0,0,0,1,1,77.75,4266.40

2200    0
4627    0
3225    0
2828    0
3768    0
Name: Churn, dtype: int64

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=0)

In [30]:
ada_cm
ada_cr
ada_score

array([[1371,  189],
       [ 243,  310]])

'              precision    recall  f1-score   support\n\n           0       0.85      0.88      0.86      1560\n           1       0.62      0.56      0.59       553\n\n    accuracy                           0.80      2113\n   macro avg       0.74      0.72      0.73      2113\nweighted avg       0.79      0.80      0.79      2113\n'

0.795551348793185

In [31]:
parameters={'learning_rate':[0.1,0.15,0.2,0.25,0.3],
            'max_depth':range(1,3)}

In [32]:
xgb_model = XGBClassifier(random_state=0)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

xgb_score = accuracy_score(y_test, y_pred)

xgb_cm = confusion_matrix(y_test, y_pred)

xgb_cr = classification_report(y_test, y_pred)

xgb_score
xgb_cm
xgb_cr

In [43]:
clf_model = GridSearchCV(estimator=xgb_model, param_grid=parameters)

clf_model.fit(X_train, y_train)

y_pred = clf_model.predict(X_test)

clf_score = accuracy_score(y_test, y_pred)

clf_cm = confusion_matrix(y_test, y_pred)

clf_cr = classification_report(y_test, y_pred)

clf_score
clf_cm
clf_cr

/Users/raisaurabh04/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='warn', n_jobs=None,
             param_grid={'learning_rate': [0.1, 0.15, 0.2, 0.25, 0.3],
                         'max_depth': range(1, 3)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

0.8017037387600567

array([[1394,  166],
       [ 253,  300]])

'              precision    recall  f1-score   support\n\n           0       0.85      0.89      0.87      1560\n           1       0.64      0.54      0.59       553\n\n    accuracy                           0.80      2113\n   macro avg       0.75      0.72      0.73      2113\nweighted avg       0.79      0.80      0.80      2113\n'