In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
# from sklearn.naive_bayes import GaussianNB
# from sklearn.svm import SVC
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.cluster import KMeans
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import GradientBoostingClassifier ,RandomForestClassifier ,GradientBoostingClassifier
# from xgboost import XGBClassifier 
# from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
# from sklearn.linear_model import Ridge,Lasso
# from sklearn.metrics import roc_auc_score ,mean_squared_error,recall_score,f1_score,accuracy_score,classification_report,roc_curve,confusion_matrix,precision_score
# from scipy.stats.mstats import winsorize
# from sklearn.feature_selection import RFE
# from sklearn.feature_selection import chi2
# from sklearn.feature_selection import f_classif
# from sklearn.feature_selection import SelectKBest
# from sklearn.decomposition import PCA
# from sklearn.model_selection import train_test_split
# from mlxtend.classifier import StackingClassifier
import datetime
import time
import swifter
import math

In [2]:
Combined_Data_AL_UTM_Reg_AU = pd.read_csv('./Data/Combined_Data_AL_UTM_Reg_AU.csv',sep=',')

In [3]:
Combined_Data_AL_UTM_Reg_AU.head(50)

,Country,Date,DateTime,Device,Event,Minute_Of_Day,OS,Second,State,Status,StrDateTime,UserId
0,1,20170221,2017-02-21 10:36:36,1,App Launched,636,1,36,36,NaN,2017-02-21 10:36:36,0000146e97c32d369268e5ba5f4b907c
1,1,20170221,2017-02-21 10:36:36,1,Registration,636,1,36,36,Completed,2017-02-21 10:36:36,0000146e97c32d369268e5ba5f4b907c
2,1,20170221,2017-02-21 12:16:20,1,App Launched,736,1,20,36,NaN,2017-02-21 12:16:20,0000146e97c32d369268e5ba5f4b907c
3,1,20170221,2017-02-21 18:16:28,1,App Launched,1096,1,28,36,NaN,2017-02-21 18:16:28,0000146e97c32d369268e5ba5f4b907c
4,1,20170221,2017-02-21 18:16:28,1,UTM Visited,1096,1,28,36,NaN,2017-02-21 18:16:28,0000146e97c32d369268e5ba5f4b907c
5,1,20170221,2017-02-21 21:31:40,1,App Launched,1291,1,40,36,NaN,2017-02-21 21:31:40,0000146e97c32d369268e5ba5f4b907c
6,1,20170222,2017-02-22 17:36:48,1,App Launched,1056,1,48,36,NaN,2017-02-22 17:36:48,0000146e97c32d369268e5ba5f4b907c
7,1,20170222,2017-02-22 20:13:20,1,App Launched,1213,1,20,36,NaN,2017-02-22 20:13:20,0000146e97c32d369268e5ba5f4b907c
8,1,20170223,2017-02-23 11:44:24,1,App Launched,704,1,24,36,NaN,2017-02-23 11:44:24,0000146e97c32d369268e5ba5f4b907c
9,1,20170223,2017-02-23 14:10:56,1,App Launched,850,1,56,36,NaN,2017-02-23 14:10:56,0000146e97c32d369268e5ba5f4b907c
10,1,20170223,2017-02-23 14:14:28,1,App Launched,854,1,28,36,NaN,2017-02-23 14:14:28,0000146e97c32d369268e5ba5f4b907c
11,1,20170225,2017-02-25 14:46:52,1,App Launched,886,1,52,36,NaN,2017-02-25 14:46:52,0000146e97c32d369268e5ba5f4b907c
12,1,20170228,2017-02-28 13:42:12,1,App Launched,822,1,12,36,NaN,2017-02-28 13:42:12,0000146e97c32d369268e5ba5f4b907c
13,1,20170228,2017-02-28 13:42:12,1,UTM Visited,822,1,12,36,NaN,2017-02-28 13:42:12,0000146e97c32d369268e5ba5f4b907c
14,1,20170228,2017-02-28 13:43:00,1,UTM Visited,823,1,0,36,NaN,2017-02-28 13:43:00,0000146e97c32d369268e5ba5f4b907c
15,1,20170228,2017-02-28 15:02:16,1,App Launched,902,1,16,36,NaN,2017-02-28 15:02:16,0000146e97c32d369268e5ba5f4b907c
16,1,20170228,2017-02-28 15:02:16,1,UTM Visited,902,1,16,36,NaN,2017-02-28 15:02:16,0000146e97c32d369268e5ba5f4b907c
17,1,20170310,2017-03-10 21:10:00,1,App Launched,1270,1,0,36,NaN,2017-03-10 21:10:00,0000146e97c32d369268e5ba5f4b907c
18,1,20170313,2017-03-13 15:43:44,1,App Launched,943,1,44,36,NaN,2017-03-13 15:43:44,0000146e97c32d369268e5ba5f4b907c
19,1,20170316,2017-03-16 02:32:00,1,App Uninstalled,152,1,0,36,NaN,2017-03-16 02:32:00,0000146e97c32d369268e5ba5f4b907c
20,14,20170207,2017-02-07 00:09:44,1,App Launched,9,1,44,1,NaN,2017-02-07 00:09:44,0000193a728fd00b6cff91b8840bbf8d
21,14,20170208,2017-02-08 04:30:04,1,App Launched,270,1,4,1,NaN,2017-02-08 04:30:04,0000193a728fd00b6cff91b8840bbf8d
22,14,20170209,2017-02-09 02:03:00,1,App Uninstalled,123,1,0,1,NaN,2017-02-09 02:03:00,0000193a728fd00b6cff91b8840bbf8d
23,40,20170213,2017-02-13 23:47:20,1,App Launched,1427,1,20,33,NaN,2017-02-13 23:47:20,00001e3213a2159ed06f1db689c54fbb
24,40,20170213,2017-02-13 23:47:24,1,Registration,1427,1,24,33,Completed,2017-02-13 23:47:24,00001e3213a2159ed06f1db689c54fbb
25,40,20170213,2017-02-13 23:47:28,1,UTM Visited,1427,1,28,33,NaN,2017-02-13 23:47:28,00001e3213a2159ed06f1db689c54fbb
26,40,20170215,2017-02-15 23:39:28,1,App Launched,1419,1,28,33,NaN,2017-02-15 23:39:28,00001e3213a2159ed06f1db689c54fbb
27,40,20170216,2017-02-16 23:38:48,1,App Launched,1418,1,48,33,NaN,2017-02-16 23:38:48,00001e3213a2159ed06f1db689c54fbb
28,40,20170219,2017-02-19 08:35:52,1,App Launched,515,1,52,33,NaN,2017-02-19 08:35:52,00001e3213a2159ed06f1db689c54fbb
29,40,20170308,2017-03-08 02:31:00,1,App Uninstalled,151,1,0,33,NaN,2017-03-08 02:31:00,00001e3213a2159ed06f1db689c54fbb
30,40,20170430,2017-04-30 21:37:56,2,App Launched,1297,1,56,33,NaN,2017-04-30 21:37:56,00004010d92c2f13b824237bc323d58b
31,40,20170430,2017-04-30 21:38:24,2,UTM Visited,1298,1,24,33,NaN,2017-04-30 21:38:24,00004010d92c2f13b824237bc323d58b
32,40,20170430,2017-04-30 21:39:40,2,Registration,1299,1,40,33,Completed,2017-04-30 21:39:40,00004010d92c2f13b824237bc323d58b
33,40,20170430,2017-04-30 21:39:52,2,UTM Visited,1299,1,52,33,NaN,2017-04-30 21:39:52,00004010d92c2f13b824237bc323d58b
34,40,20170502,2017-05-02 21:00:00,2,App Uninstalled,1260,1,0,33,NaN,2017-05-02 21:00:00,00004010d92c2f13b824237bc323d58b
35,1,20170506,2017-05-06 14:23:24,1,App Launched,863,1,24,35,NaN,2017-05-06 14:23:24,00004dd911aafdc3f3cd64a490bd56f1
36,1,20170506,2017-05-06 14:23:24,1,UTM Visited,863,1,24,35,NaN,2017-05-06 14:23:24,00004dd911aafdc3f3cd64a490bd56f1
37,1,20170507,2017-05-07 11:31:20,1,App Launched,691,1,20,35,NaN,2017-05-07 11:31:20,00004dd911aafdc3f3cd64a490bd56f1
38,1,20170507,2017-05-07 14:22:00,1,App Uninstalled,862,1,0,35,NaN,2017-05-07 14:22:00,00004dd911aafdc3f3cd64a490bd56f1
39,1,20170609,2017-06-09 19:58:48,1,App Launched,1198,2,48,35,NaN,2017-06-09 19:58:48,000076c7bbdf7e4568777134cc4bec56
40,1,20170609,2017-06-09 19:58:48,1,Registration,1198,2,48,35,Complete,2017-06-09 19:58:48,000076c7bbdf7e4568777134cc4bec56
41,1,20170610,2017-06-10 20:16:40,1,App Launched,1216,2,40,35,NaN,2017-06-10 20:16:40,000076c7bbdf7e4568777134cc4bec56
42,1,20170610,2017-06-10 22:17:52,1,App Launched,1337,2,52,35,NaN,2017-06-10 22:17:52,000076c7bbdf7e4568777134cc4bec56
43,1,20170610,2017-06-10 22:18:24,1,UTM Visited,1338,2,24,35,NaN,2017-06-10 22:18:24,000076c7bbdf7e4568777134cc4bec56
44,1,20170610,2017-06-10 23:44:12,1,App Launched,1424,2,12,35,NaN,2017-06-10 23:44:12,000076c7bbdf7e4568777134cc4bec56
45,1,20170610,2017-06-10 23:47:00,1,App Launched,1427,2,0,35,NaN,2017-06-10 23:47:00,000076c7bbdf7e4568777134cc4bec56
46,1,20170611,2017-06-11 10:29:36,1,App Launched,629,2,36,35,NaN,2017-06-11 10:29:36,000076c7bbdf7e4568777134cc4bec56
47,1,20170612,2017-06-12 00:50:04,1,App Launched,50,2,4,35,NaN,2017-06-12 00:50:04,000076c7bbdf7e4568777134cc4bec56
48,1,20170612,2017-06-12 05:43:28,1,App Launched,343,2,28,35,NaN,2017-06-12 05:43:28,000076c7bbdf7e4568777134cc4bec56
49,1,20170612,2017-06-12 23:09:40,1,App Launched,1389,2,40,35,NaN,2017-06-12 23:09:40,000076c7bbdf7e4568777134cc4bec56

In [4]:
Combined_Data_AL_UTM_Reg_AU['Genre'] = "NA"
Combined_Data_AL_UTM_Reg_AU['Category'] = "NA"
Combined_Data_AL_UTM_Reg_AU['ProgramType'] = "NA"
Combined_Data_AL_UTM_Reg_AU['VideoId'] = "NA"

In [5]:
VideoDetailsMod=pd.read_csv('./Data/VideoDetailsMod.csv',sep=',')
VideoStartedMod=pd.read_csv('./Data/VideoStartedMod.csv',sep=',')

In [6]:
VideoDetailsMod['Status'] = "NA"
VideoStartedMod['Status'] = "NA"

In [7]:
VideoDetailsMod['Event'] = "Video Details"
VideoStartedMod['Event'] = "Video Started"

In [8]:
Combined_Data_AL_UTM_Reg_AU = Combined_Data_AL_UTM_Reg_AU.append(VideoDetailsMod,ignore_index=True)
Combined_Data_AL_UTM_Reg_AU = Combined_Data_AL_UTM_Reg_AU.append(VideoStartedMod,ignore_index=True)

In [9]:
Combined_Data_AL_UTM_Reg_AU.sort_values(['UserId','DateTime','Event'],axis=0,inplace=True)

In [10]:
Combined_Data_AL_UTM_Reg_AU.to_csv(path_or_buf='./Data/Combined_Data.csv',sep=',',index=False)